"""Markdown report assembly."""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from pathlib import Path

from .analysis import column_summary

logger = logging.getLogger("sift_agent.report")


def write_report(state: dict) -> str:
    """Write report.md + profile.json into the output dir; return the report path."""
    out_dir = Path(state["output_dir"])
    profile = state["profile"]
    charts = state.get("charts") or []
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "profile.json").write_text(
        json.dumps(profile, indent=2, default=str), encoding="utf-8"
    )

    provider = state.get("provider") or "none"
    model = state.get("model") or ""
    llm_label = model or (
        "heuristic (offline)" if provider == "none" else "provider default"
    )

    lines: list[str] = []
    lines.append(f"# Auto-EDA report — {Path(state['csv_path']).name}")
    lines.append("")
    lines.append(
        f"*Generated {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')} "
        f"· provider `{provider}` · model `{llm_label}`*"
    )
    lines.append("")

    lines.append("## Overview")
    lines.append("")
    lines.append("| metric | value |")
    lines.append("|---|---|")
    lines.append(f"| rows | {profile['n_rows']:,} |")
    lines.append(f"| columns | {profile['n_columns']} |")
    lines.append(f"| numeric columns | {profile['n_numeric_columns']} |")
    lines.append(f"| categorical columns | {profile['n_categorical_columns']} |")
    lines.append(f"| duplicate rows | {profile['duplicate_rows']:,} |")
    lines.append(f"| memory | {profile['memory_mb']} MB |")
    lines.append("")

    missing = profile.get("top_missing") or []
    lines.append("## Missing values")
    lines.append("")
    if missing:
        lines.append("| column | missing | % |")
        lines.append("|---|---|---|")
        for m in missing:
            lines.append(
                f"| `{m['column']}` | {m['n_missing']:,} | {m['pct_missing']}% |"
            )
    else:
        lines.append("No missing values detected.")
    lines.append("")

    lines.append("## Column profiles")
    lines.append("")
    lines.append("| column | type | dtype | missing % | unique | summary |")
    lines.append("|---|---|---|---|---|---|")
    n_columns = len(profile["columns"])
    for name, c in list(profile["columns"].items())[:60]:
        summary = column_summary(c)
        lines.append(
            f"| `{name}` | {c.get('type', '?')} | {c['dtype']} | {c['pct_missing']}% | {c['n_unique']:,} | {summary} |"
        )
    lines.append("")
    if n_columns > 60:
        lines.append(f"*Showing the first 60 of {n_columns} columns.*")
        lines.append("")

    warnings = state.get("warnings") or []
    if warnings:
        lines.append("## Warnings")
        lines.append("")
        for w in warnings:
            lines.append(f"- {w}")
        lines.append("")

    corr = profile.get("top_correlated_pairs") or []
    if corr:
        lines.append("## Strongest correlations")
        lines.append("")
        lines.append("| col a | col b | pearson r |")
        lines.append("|---|---|---|")
        for p in corr:
            lines.append(f"| `{p['col_a']}` | `{p['col_b']}` | {p['pearson_r']:+.2f} |")
        lines.append("")

    if charts:
        lines.append("## Visualizations")
        lines.append("")
        for ch in charts:
            lines.append(f"### {ch['title']}")
            lines.append("")
            lines.append(f"![{ch['title']}]({ch['path']})")
            lines.append("")
            lines.append(f"*{ch['caption']}*")
            lines.append("")

    lines.append("## Key insights")
    lines.append("")
    lines.append(state.get("insights") or "_no insights generated_")
    lines.append("")
    lines.append("## Recommendations")
    lines.append("")
    lines.append(state.get("recommendations") or "_no recommendations generated_")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by sift-agent — auto-EDA with LangGraph.*")

    report_path = out_dir / "report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("report written: %s", report_path)
    return str(report_path)
